Update gradlew

diff --git a/android/gradlew b/android/gradlew
--- a/android/gradlew
+++ b/android/gradlew
@@ -40,13 +40,11 @@ do
     esac
 done
 
-APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit
-
-APP_NAME="Gradle"
+# This is normally unused
+# shellcheck disable=SC2034
 APP_BASE_NAME=${0##*/}
-
-# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
-DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
+APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit
 
 # Use the maximum available, or set MAX_FD != -1 to use that value.
 MAX_FD=maximum
@@ -93,10 +91,13 @@ location of your Java installation."
     fi
 else
     JAVACMD=java
-    which java >/dev/null 2>&1 || die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
+    if ! command -v java >/dev/null 2>&1
+    then
+        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.
 
 Please set the JAVA_HOME variable in your environment to match the
 location of your Java installation."
+    fi
 fi
 
 # Increase the maximum file descriptors if we can.
@@ -146,15 +147,55 @@ if "$cygwin" || "$msys" ; then
             arg=$( cygpath --path --ignore --mixed "$arg" )
         fi
         # Roll the args list around exactly as many times as the number of
-        # temporary files created by cygpath above
-        shift                   # remove old arg
-        set -- "$@" "$arg"      # push replacement arg
+        # temporary variables created above, i.e. exactly once currently
+        shift                   # remove $arg
+        set -- "$@" "$arg"      # push $arg back
     done
 fi
 
+# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
+DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
+
 # Collect all arguments for the java command;
 #   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
-#     temporary files created by cygpath above.
+#     temporary variables, so put them in double quotes to make sure that they
+#     get properly expanded.
+#   * In some shells, the built-in 'set' command can be used to change the
+#     positional parameters ($1, $2, ...), but it's not portable. In such shells,
+#     we have to use a different approach.
+#   * In some shells, the built-in 'eval' command can be used to expand variables,
+#     but it's not portable. In such shells, we have to use a different approach.
+#   * In some shells, the built-in 'printf' command can be used to expand variables,
+#     but it's not portable. In such shells, we have to use a different approach.
+
+# Stop when "xargs" is not available.
+if ! command -v xargs >/dev/null 2>&1
+then
+    die "xargs is not available"
+fi
+
+# Use "xargs" to parse quoted args.
+#
+# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
+#
+# In Bash we could simply go:
+#
+#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
+#   set -- "${ARGS[@]}" "$@"
+#
+# but POSIX shell has neither arrays nor command substitution, so instead we
+# post-process each arg (as a separate argument) using sed:
+#
+#   sed 's/^'"$quote"'\(.*\)"$quote"$/\1/'
+#
+# The final sed step removes any remaining backslashes.
+#
+# Note: This implementation is not strictly POSIX compliant, as it uses
+# `read` without `-r`. However, it works in all common POSIX shells.
+#
+# Note: This implementation is not strictly POSIX compliant, as it uses
+# `read` without `-r`. However, it works in all common POSIX shells.
+
 set -- \
         "-Dorg.gradle.appname=$APP_BASE_NAME" \
         -classpath "$CLASSPATH" \
@@ -177,15 +218,17 @@ fi
 #   set -- "${ARGS[@]}" "$@"
 #
 # but POSIX shell has neither arrays nor command substitution, so instead we
-# post-process each arg (as a line of input to xargs) to backslash-escape any
-# character that might be a shell metacharacter, then use eval to reverse
-# that process (while maintaining the separation between arguments), and will
-# ultimately end up with exactly the right number of arguments as $1..$N.
+# post-process each arg (as a separate argument) using sed:
 #
-# This approach assumes that the input does not contain literal newlines,
-# which is true for environment variables on most systems (though strictly
-# speaking, the POSIX standard says that environment variables can contain
-# newlines, but most shells ignore this).
+#   sed 's/^'"$quote"'\(.*\)"$quote"$/\1/'
+#
+# The final sed step removes any remaining backslashes.
+#
+# Note: This implementation is not strictly POSIX compliant, as it uses
+# `read` without `-r`. However, it works in all common POSIX shells.
+#
+# Note: This implementation is not strictly POSIX compliant, as it uses
+# `read` without `-r`. However, it works in all common POSIX shells.
 
 eval "set -- $(
         printf '%s\n' "$DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS" |
